spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/subway?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: masterpw
    hikari:
      max-lifetime: 58000
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379


  jpa:
    properties:
      hibernate:
        dialect:
          show_sql: true
          nodeValue: org.hibernate.dialect.MySQL57Dialect
          storage_engine: innodb

